/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   c-curl-http-snippet.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-repeat.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="code-snippets-mixin.d.ts" />
/// <reference path="http-code-snippets-style.d.ts" />

declare namespace ApiElements {

  /**
   * `c-curl-http-snippet`
   *
   * A snippet for requests made in C using curl library.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class CcurlHttpSnippet extends
    ArcBehaviors.CodeSnippetsMixin(
    Polymer.Element) {
    readonly payloadLines: any[]|null|undefined;
    readonly hasPayloadLines: boolean|null|undefined;
    _payloadChanged(payload: any): any;
    _isFirst(i: any): any;
    _isFirstOrLast(i: any, arr: any): any;
    _isLast(i: any, arr: any): any;
  }
}

interface HTMLElementTagNameMap {
  "c-curl-http-snippet": ApiElements.CcurlHttpSnippet;
}
