/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   code-snippets-mixin.html
 */

/// <reference path="../polymer/types/lib/utils/mixin.d.ts" />

declare namespace ArcBehaviors {


  /**
   * Common properties for HTTP code snippets.
   */
  function CodeSnippetsMixin<T extends new (...args: any[]) => {}>(base: T): T & CodeSnippetsMixinConstructor;

  interface CodeSnippetsMixinConstructor {
    new(...args: any[]): CodeSnippetsMixin;
  }

  interface CodeSnippetsMixin {

    /**
     * The URL of the request
     */
    url: string|null|undefined;

    /**
     * HTTP method
     */
    method: string|null|undefined;

    /**
     * HTTP headers
     */
    headers: string|null|undefined;

    /**
     * HTTP body (message)
     */
    payload: string|null|undefined;

    /**
     * Computes a list of headers from a headers string.
     *
     * @returns Headers as a list od maps. Can be empty.
     */
    headersToList(headers: String|null): any[]|null;

    /**
     * Reads the host, port and path from the url.
     * This function uses URI library to parse the URL so you have to
     * include this library from bower_components if the element want to use it.
     */
    urlDetails(url: any): any;
  }
}
