/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   http-code-snippets.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

declare namespace ApiElements {

  /**
   * `http-code-snippets`
   *
   * Code snippets to display code implementatyion examples for a HTTP request
   *
   * ## Polyfills
   *
   * This component requires `advanced-rest-client/URL` (or other) polyfill for
   * URL object. This spec is not supported in Safari 9 and IE 11.
   * If you are targeting this browsers install ind include this dependency.
   *
   * This component does not include polyfills.
   *
   * ## Styling
   *
   * See http-code-snippets-style.js file for styling definition.
   */
  class HttpCodeSnippets extends LitElement {

    /**
     * Parsed HTTP headers.
     * Each item contains `name` and `value` properties.
     */
    headers: string|null|undefined;

    /**
     * Currently selected tab for the platform row.
     */
    selected: number|null|undefined;

    /**
     * Computed list of headers from `headers` property.
     * It is an array of objects where each object contains `name` and `value`
     * properties.
     */
    _headersList: Array<object|null>|null;

    /**
     * Passed to `anypoint-tabs` `scrollable` property
     */
    scrollable: boolean|null|undefined;

    /**
     * Request URL
     */
    url: string|null|undefined;

    /**
     * HTTP method
     */
    method: string|null|undefined;

    /**
     * HTTP body (the message)
     */
    payload: string|null|undefined;

    /**
     * Enables compatibility with Anypoint components.
     */
    compatibility: boolean|null|undefined;
    constructor();
    render(): any;
    _snippetTemplate(): any;

    /**
     * Handler for `selected-changed` event dispatched on anypoint-tabs.
     */
    _selectedCHanged(e: CustomEvent|null): void;

    /**
     * Computes a list of headers from a headers string.
     *
     * @returns Headers as a list od maps. Can be empty.
     */
    headersToList(headers: String|null): any[]|null;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "http-code-snippets": ApiElements.HttpCodeSnippets;
  }
}
