/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   http-code-snippets.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-tabs/paper-tabs.d.ts" />
/// <reference path="../paper-tabs/paper-tab.d.ts" />
/// <reference path="../iron-pages/iron-pages.d.ts" />
/// <reference path="raw-http-snippet.d.ts" />
/// <reference path="curl-http-snippet.d.ts" />
/// <reference path="javascript-http-snippets.d.ts" />
/// <reference path="python-http-snippets.d.ts" />
/// <reference path="c-curl-http-snippet.d.ts" />
/// <reference path="code-snippets-mixin.d.ts" />

declare namespace ApiElements {

  /**
   * `http-code-snippets`
   *
   * Code snippets to display code implementatyion examples for a HTTP request
   *
   * ## Polyfills
   *
   * This component requires `github/url-polyfill` (or other) polyfill for
   * URL object. This spec is not supported in Safari 9 and IE 11.
   * If you are targeting this browsers install ind include this dependency.
   *
   * This component does not include polyfills.
   *
   * ## Styling
   *
   * `<http-code-snippets>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class HttpCodeSnippets extends
    ArcBehaviors.CodeSnippetsMixin(
    Polymer.Element) {

    /**
     * Currently selected tab for the platform row.
     */
    selectedPlatform: number|null|undefined;

    /**
     * A list of HTTP headers from the headers string
     */
    readonly headersList: any[]|null|undefined;
  }
}

interface HTMLElementTagNameMap {
  "http-code-snippets": ApiElements.HttpCodeSnippets;
}
