/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   java-spring-http-snippet.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="code-snippets-mixin.d.ts" />
/// <reference path="http-code-snippets-style.d.ts" />

declare namespace ApiElements {

  /**
   * `java-spring-http-snippet`
   *
   * A snippet for requests made in Java using the spring functions
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class JavaSpringHttpSnippet extends
    ArcBehaviors.CodeSnippetsMixin(
    Polymer.Element) {
    _payloadToList(payload: any): any;
  }
}

interface HTMLElementTagNameMap {
  "java-spring-http-snippet": ApiElements.JavaSpringHttpSnippet;
}
