/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   python-27-http-snippet.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-repeat.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="code-snippets-mixin.d.ts" />
/// <reference path="http-code-snippets-style.d.ts" />

declare namespace ApiElements {

  /**
   * `python-27-http-snippet`
   *
   * A snippet for requests made in Python 2.7 using native library.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class Python27HttpSnippet extends
    ArcBehaviors.CodeSnippetsMixin(
    Polymer.Element) {

    /**
     * True if this is a SSL based request
     */
    readonly isTls: string|null|undefined;

    /**
     * HTTP path value
     */
    path: string|null|undefined;

    /**
     * HTTP host name
     */
    hostValue: string|null|undefined;

    /**
     * Connection port value
     */
    port: number|null|undefined;
    _urlChanged(url: any): void;
    _isLast(index: any, array: any): any;
  }
}

interface HTMLElementTagNameMap {
  "python-27-http-snippet": ApiElements.Python27HttpSnippet;
}
