/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   python-http-snippets.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-tabs/paper-tabs.d.ts" />
/// <reference path="../paper-tabs/paper-tab.d.ts" />
/// <reference path="../iron-pages/iron-pages.d.ts" />
/// <reference path="requests-python-http-snippet.d.ts" />
/// <reference path="python-27-http-snippet.d.ts" />
/// <reference path="python-31-http-snippet.d.ts" />
/// <reference path="code-snippets-mixin.d.ts" />

declare namespace ApiElements {

  /**
   * `raw-http-snippet`
   *
   * A set of code snippets for Python requests.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class PythonHttpSnippets extends
    ArcBehaviors.CodeSnippetsMixin(
    Polymer.Element) {
    selectedFramework: number|null|undefined;
  }
}

interface HTMLElementTagNameMap {
  "python-http-snippets": ApiElements.PythonHttpSnippets;
}
