/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   python-http-snippets.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

declare namespace ApiElements {

  /**
   * `raw-http-snippet`
   *
   * A set of code snippets for Python requests.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class PythonHttpSnippets extends LitElement {
    selected: number|null|undefined;

    /**
     * Request URL
     */
    url: string|null|undefined;

    /**
     * HTTP method
     */
    method: string|null|undefined;

    /**
     * Parsed HTTP headers.
     * Each item contains `name` and `value` properties.
     */
    headers: Array<object|null>|null;

    /**
     * HTTP body (the message)
     */
    payload: string|null|undefined;

    /**
     * Enables compatibility with Anypoint components.
     */
    compatibility: boolean|null|undefined;
    constructor();
    render(): any;
    _renderPage(selected: any): any;

    /**
     * Handler for `selected-changed` event dispatched on anypoint-tabs.
     */
    _selectedCHanged(e: CustomEvent|null): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "python-http-snippets": ApiElements.PythonHttpSnippets;
  }
}
