/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   xhr-http-snippet.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-repeat.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="code-snippets-mixin.d.ts" />
/// <reference path="http-code-snippets-style.d.ts" />

declare namespace ApiElements {

  /**
   * `raw-http-snippet`
   *
   * A snippet for requests made in JavaScript using XHR object.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--http-code-snippets` | Mixin applied to this elment | `{}`
   */
  class XhrHttpSnippet extends
    ArcBehaviors.CodeSnippetsMixin(
    Polymer.Element) {
    readonly payloadLines: any[]|null|undefined;
    readonly hasPayloadLines: boolean|null|undefined;
    _re: object|null|undefined;
    _payloadChanged(payload: any): any;
  }
}

interface HTMLElementTagNameMap {
  "xhr-http-snippet": ApiElements.XhrHttpSnippet;
}
